service: serverless

package:
  exclude: 
    - node_modules/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  apiName: GenommaLab
  vpc:
    securityGroupsdIds:
      - sg-77b00f2e
    subnetsIds:
      - subnet-e2a134dc
      - subnet-4b317317
  

functions:
  GetDataMasterInventario:
    handler: handler.GetDataMasterInventario
    events:
      - http:
          path: genommalab/supplychain/get-data-master-inventario/{provider}
          method: get
          cors: true
  AddDataProvider:
    handler: handler.AddDataProvider
    events:
      - http:
          path: genommalab/supplychain/add-data-provider
          method: post
          cors: true
  GetDataProvider:
    handler: handler.GetDataProvider
    events:
      - http:
          path: genommalab/supplychain/get-data-provider/{provider}
          method: get
          cors: true
  AddDataMasterInventario:
    handler: handler.AddDataMasterInventario
    events:
      - http:
          path: genommalab/supplychain/add-data-master-inventario
          method: post
          cors: true
  ContactUs:
    handler: handler.ContactUs
    events:
      - http:
          path: genommalab/supplychain/contact-us
          method: post
          cors: true

